// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npiwmxbftwwgyowngyxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5waXdteGJmdHd3Z3lvd25neXhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1OTYxMzksImV4cCI6MjA1MTE3MjEzOX0.Ffn8txmU39U3Wgn2v7t2zfAvoDl0VGHxu3mwD-yPhc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);